---
siteInfo:
  - 
    jobListings: 'article ul li'
    jobTitle: 'span.title'
    site: 'https://weworkremotely.com/categories/remote-programming-jobs'
  - 
    jobListings: 'div[data-jobid]'
    jobTitle: 'h2 a'
    site: 'https://stackoverflow.com/jobs?r=true&j=permanent'
  - 
    jobListings: 'tbody tr[id]'
    jobTitle: 'a h2'
    site: 'https://remoteok.io/remote-dev-jobs'
  - 
    jobListings: '#jobs div.job'
    jobTitle: 'a h2'
    site: 'https://www.workingnomads.co/jobs?category=development'
  - 
    jobListings: 'div.job_listings ul.job_listings li'
    jobTitle: 'a'
    site: 'https://jobspresso.co/remote-software-jobs/'